[book]
title = "Dragon's Egg & Starquake"
authors = ["Robert L. Forward"]
language = "en"
multilingual = false
src = "src"

[output.html]
site-url = "/cheela/"
default-theme = "rust"
preferred-dark-theme = "ayu"
curly-quotes = true
no-section-label = true
git-repository-url = "https://github.com/mdPub/cheela"
